# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: wadoon/verifaps-test:latest
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: "Versions"
          command: |
            javac -version
            z3 -version
            echo $(echo "quit" | nuXmv -int | head -n 1)

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies
      - run: gradle classes
      - run: gradle testClasses

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle --continue check

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

#      - store_artifacts:
#          path: ~/junit

  integration-tests:
    docker:
      - image: wadoon/verifaps-test:latest
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: "Versions"
          command: |
            javac -version
            z3 -version
            echo $(echo "quit" | nuXmv -int | head -n 1)

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.gradle
            - build
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle :ide:assembleDist

      - run:
          name: Integration Tests
          command: |
            which nuXmv
            which z3
            share/integration-tests.sh

      - store_artifacts:
          path: ide/build/distributions/*